security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    providers:
        users_in_database:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            entry_point: form_login
            lazy: true
            provider: users_in_database
            form_login:
                login_path: app_login  # Исправлено: Symfony ожидает имя маршрута
                check_path: app_login
                csrf_token_id: authenticate
                csrf_parameter: _csrf_token
            logout:
                path: app_logout  # Исправлено: имя маршрута должно соответствовать контроллеру
                target: app_login  # Перенаправление после выхода
                invalidate_session: true
            custom_authenticator: App\Security\AppCustomAuthenticator

            remember_me:
                secret: '%kernel.secret%'
                lifetime: 604800
                path: /
                always_remember_me: true

    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/profile, roles: ROLE_USER }

when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4
                time_cost: 3
                memory_cost: 10
