security:
    # Настройка хеширования паролей
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    # Настройка провайдера пользователей, используемого для поиска в базе данных
    providers:
        users_in_database:
            entity:
                class: App\Entity\User
                property: email  # Указываем поле для поиска пользователя (например, email)

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            # Указываем точку входа для анонимных пользователей
            entry_point: form_login  # Используем form_login для анонимных пользователей
            lazy: true
            provider: users_in_database  # Используем провайдер, настроенный для поиска пользователей в БД
            form_login:
                login_path: login  # Путь к странице входа
                check_path: login  # Путь для отправки формы логина
                csrf_token_id: authenticate  # Подтверждение CSRF
                csrf_parameter: _csrf_token  # Параметр для CSRF
            logout:
                path: logout  # Путь для выхода
                invalidate_session: true  # Инвалидация сессии после выхода
            custom_authenticator: App\Security\AppCustomAuthenticator  # Указываем свой аутентификатор

            remember_me:
                secret: '%kernel.secret%'
                lifetime: 604800
                path: /
                always_remember_me: true
            # Вы можете включить impersonation (персонализация), если требуется
            # switch_user: true

    # Контроль доступа на основе ролей
    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }  # Доступ к /admin только для пользователей с ролью ROLE_ADMIN
        - { path: ^/profile, roles: ROLE_USER }  # Доступ к /profile только для пользователей с ролью ROLE_USER

# Специальная настройка для тестов (не влияет на продакшн)
when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4
                time_cost: 3
                memory_cost: 10
